version: "3"
services:
  envoy:
    image: envoyproxy/envoy-dev:b136310d14ceb5ce66c96ac6b3b2f445aac943e7
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"
  redis:
    image: bitnami/redis
    volumes:
      - ./data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"