version: "3"
services:
  envoy:
    image: envoyproxy/envoy:v1.14.1
    volumes:
      - ./test.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"
    restart: unless-stopped